version: '3.8'
services:
  db:
    image: postgres:15
    container_name: server-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: cropco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

    volumes:
      - ./data-server-db:/var/lib/postgresql/data
    restart: always
