services:
  nest-api:
    image: stivenc30/backend-cropco:deployment
    container_name: nest-api
    ports:
      - 3000:3000
    environment:
      - DB_HOST=dpg-d0of8nidbo4c73erpcr0-a.oregon-postgres.render.com
      - DB_PORT=5432
      - DB_USERNAME=admin_cropco
      - DB_PASSWORD=Dr2NGA9WK4WedpqARuBeDpPqM4lAwEAe
      - DB_NAME=cropco_db_t928
      - JWT_SECRET=millavesecreta
      - PORT=3000
      - HOST_FRONTED=http://localhost:5173
