services:
  server-db:
    image: postgres:15
    container_name: server-db
    environment:
      POSTGRES_DB: cropco_management
      POSTGRES_USER: admin-cropco
      POSTGRES_PASSWORD: oBg24_7u9f32
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d cropco']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data-server-db-development:/var/lib/postgresql/data
      # - ./sql-scripts:/docker-entrypoint-initdb.d/
