name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Crear directorio de certificados
        run: mkdir -p certs

      - name: Escribir archivo .crt
        run: echo "${{ secrets.CERT_CRT }}" > certs/ca-certificate.crt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Limpiar caché de Docker
        run: |
          docker builder prune -f
          docker system prune -f

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          no-cache: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cropco-api-rest:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
